Traceback (most recent call last):
  File "C:\Users\nguyen0004\AppData\Roaming\Python\Python37\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\nguyen0004\AppData\Roaming\Python\Python37\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\nguyen0004\AppData\Roaming\Python\Python37\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\nguyen0004\AppData\Roaming\Python\Python37\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\nguyen0004\Anaconda3\envs\rir\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\nguyen0004\AppData\Roaming\Python\Python37\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\nguyen0004\AppData\Roaming\Python\Python37\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\nguyen0004\AppData\Roaming\Python\Python37\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
image_size = (250, 250)
scale = 0

noise = np.zeros((2, *image_size))

noise[0] = scale * np.random.randn(*image_size)
noise[1] = scale * np.random.randn(*image_size)

# noise[1] = -noise[0] # homework

from pathlib import Path
result = list(Path('/Users/dokman0000/Downloads/lfw/').rglob('*.jpg'))

n_train = 1000
n_test = 100
images = np.zeros((n_train, 250, 250))
labels = np.zeros((n_train,), dtype=np.int8)

images_test = np.zeros((n_test, 250, 250))
labels_test = np.zeros((n_test,), dtype=np.int8)

shuffle_idx = np.random.permutation(n_train + n_test)
for i in range(n_train):
    images[i] = plt.imread(result[shuffle_idx[i]]).mean(axis=2)
    labels[i] = np.round(np.random.rand())
    images[i] += noise[labels[i]]

for i in range(n_train, n_train + n_test):
    images_test[i - n_train] = plt.imread(result[shuffle_idx[i]]).mean(axis=2)
    labels_test[i - n_train] = np.round(np.random.rand())
    # no noise in the test set!
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mIndexError[0m                                Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_6668\3183128166.py[0m in [0;36m<module>[1;34m[0m
[0;32m     22[0m [0mshuffle_idx[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0mrandom[0m[1;33m.[0m[0mpermutation[0m[1;33m([0m[0mn_train[0m [1;33m+[0m [0mn_test[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     23[0m [1;32mfor[0m [0mi[0m [1;32min[0m [0mrange[0m[1;33m([0m[0mn_train[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 24[1;33m     [0mimages[0m[1;33m[[0m[0mi[0m[1;33m][0m [1;33m=[0m [0mplt[0m[1;33m.[0m[0mimread[0m[1;33m([0m[0mresult[0m[1;33m[[0m[0mshuffle_idx[0m[1;33m[[0m[0mi[0m[1;33m][0m[1;33m][0m[1;33m)[0m[1;33m.[0m[0mmean[0m[1;33m([0m[0maxis[0m[1;33m=[0m[1;36m2[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     25[0m     [0mlabels[0m[1;33m[[0m[0mi[0m[1;33m][0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0mround[0m[1;33m([0m[0mnp[0m[1;33m.[0m[0mrandom[0m[1;33m.[0m[0mrand[0m[1;33m([0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     26[0m     [0mimages[0m[1;33m[[0m[0mi[0m[1;33m][0m [1;33m+=[0m [0mnoise[0m[1;33m[[0m[0mlabels[0m[1;33m[[0m[0mi[0m[1;33m][0m[1;33m][0m[1;33m[0m[1;33m[0m[0m

[1;31mIndexError[0m: list index out of range
IndexError: list index out of range

